"use client";
import React,{useState} from "react";
import {ChevronDown,Languages,Volume2,X,List,ArrowLeft} from "lucide-react";
import type {LibrarySenseCardGroupModel,LibrarySenseCardModel,LibrarySenseContent} from "@/components/training/library-v2/librarySenseCardModel";
import {SenseCardReveal} from "@/components/training/SenseCardChrome";
import s from "./library.module.css";
export type Nesting="plain"|"blocks";
export function LibraryButton({children,primary=false,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{primary?:boolean}){return <button {...props} className={`${s.button} ${primary?s.primary:""} ${props.className||""}`}>{children}</button>}
export function LibraryIconButton({label,children,...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{label:string}){return <button {...props} aria-label={label} title={label} className={s.iconButton}>{children}</button>}
export function Metadata({pos,core,source}:{pos:string|null;core?:string|null;source?:string}){return <span className={s.metadata}><span className={s.pos}><i/>{pos}</span>{core&&<span className={s.badge}>{core}</span>}{source&&<span className={s.source}>{source}</span>}</span>}
function ContentNode({node}:{node:LibrarySenseContent}){return <div className={s.contentNode} data-kind={node.kind}><p className={node.kind==="example"||node.kind==="idiom"?s.literary:s.explanation}>{node.text}</p>{node.children.length>0&&<div className={s.children}>{node.children.map(child=><ContentNode key={child.contentNodeId} node={child}/>)}</div>}</div>}
function MeaningCard({meaning,defaultOpen,onNotice}:{meaning:LibrarySenseCardModel;defaultOpen:boolean;onNotice:(s:string)=>void}){
 const [open,setOpen]=useState(defaultOpen);const [state,setState]=useState<"new"|"learning"|"known">("new");const [collection,setCollection]=useState(false);const [picker,setPicker]=useState(false);
 const examples=meaning.details.filter(x=>x.kind==="example");const other=meaning.details.filter(x=>x.kind!=="example");
 return <article className={s.meaningCard} data-expanded={open}><button className={s.meaningLead} aria-expanded={open} onClick={()=>setOpen(!open)}><span className={s.ordinal}>{meaning.displayOrdinal}</span><span>{meaning.definition?.text||"Expression"}</span><span className={s.state}>{state==="new"?"New":state==="learning"?"Learning":"Known"}</span><ChevronDown size={14} className={open?s.rotated:""}/></button>
 <SenseCardReveal open={open}><div className={s.meaningBody} inert={!open} aria-hidden={!open}>{meaning.definition?.children.map(n=><ContentNode key={n.contentNodeId} node={n}/>)}{examples.length>0&&<section className={s.contentSection}><h3>Examples</h3>{examples.map(n=><ContentNode key={n.contentNodeId} node={n}/>)}</section>}{other.length>0&&<section className={s.contentSection}><h3>Expressions & usage</h3>{other.map(n=><ContentNode key={n.contentNodeId} node={n}/>)}</section>}
 <div className={s.actions}>{state==="new"?<><LibraryButton primary onClick={()=>{setState("learning");onNotice("Learning · demo state only");}}>Learn</LibraryButton><LibraryButton onClick={()=>{setState("known");onNotice("Known · demo state only");}}>Mark as known</LibraryButton></>:<><LibraryButton primary onClick={()=>onNotice("Train next · no real session is started")}>Train next</LibraryButton><LibraryButton onClick={()=>{setState("new");onNotice("Reset · demo state only");}}>Reset demo</LibraryButton></>}</div>
 <div className={s.secondaryActions}><button aria-expanded={picker} onClick={()=>setPicker(!picker)}><List size={14}/>Collections{collection?" · 1":""}</button></div>{picker&&<div className={s.collectionPicker}><label><input type="checkbox" checked={collection} onChange={e=>setCollection(e.target.checked)}/> Everyday Dutch</label><button onClick={()=>setPicker(false)}>Done</button></div>}
 </div></SenseCardReveal></article>;
}
export function LibraryArticle({model,source,nesting,onClose}:{model:LibrarySenseCardGroupModel;source:string;nesting:Nesting;onClose:()=>void}){
 const [notice,setNotice]=useState("");return <article className={s.detail} data-nesting={nesting} aria-label="Word details"><header className={s.articleHeader}><div className={s.articleMeta}><Metadata pos={model.partOfSpeech} core={model.coreVocabularyLabel} source={source}/><LibraryIconButton label="Close word details" onClick={onClose}><X size={16}/></LibraryIconButton></div><div className={s.headwordRow}><h2>{model.article&&<span>{model.article} </span>}{model.headword}</h2><div className={s.headerActions}><LibraryIconButton label="Translate" onClick={()=>setNotice("Translation preview · no request is sent")}><Languages size={16}/></LibraryIconButton><LibraryIconButton label="Play audio" onClick={()=>setNotice("Audio preview · no request is sent")}><Volume2 size={16}/></LibraryIconButton></div></div><button className={s.mobileBack} onClick={onClose}><ArrowLeft size={14}/> Back to results</button></header><div className={s.meaningScroll} tabIndex={0} aria-label="Meanings">{model.meanings.map((m,i)=><MeaningCard key={m.entryId} meaning={m} defaultOpen={i===0} onNotice={setNotice}/>)}</div>{notice&&<p className={s.notice} role="status">{notice}</p>}</article>;
}
