"use client";
import React,{useEffect,useRef,useState} from "react";
import {ArrowLeft,ChevronRight,Check,ChevronUp,Languages,Palette,Keyboard,UserRound,Library,CreditCard,ChevronDown} from "lucide-react";
import {getTrainingHotkeys} from "@/components/training/trainingHotkeys";
import {textSizes} from "@/lib/reading/textScale";
import type {usePreviewTextSize} from "./usePreviewTextSize";
import {LanguagePicker} from "./LanguagePicker";
import {LibraryArticle} from "./LibraryArticle";
import {goedGroups} from "./GoedLibraryPreview";
import {studyDefaults} from "./libraryStudy";
import libraryStyles from "./library.module.css";
import s from "./settings.module.css";
import {practicePalettes, type PracticePalette, type PracticeColourMode} from "@/components/practice/ui/appearance";
import themeStyles from "@/components/practice/ui/practiceTheme.module.css";
const sections=[{name:"Languages",Icon:Languages},{name:"Dictionaries",Icon:Library},{name:"Appearance",Icon:Palette},{name:"Shortcuts",Icon:Keyboard},{name:"Billing & subscriptions",Icon:CreditCard},{name:"Account",Icon:UserRound}];
export function SettingsPrototype({textSize,resolvedDark,palette,onPaletteChange,mode,onModeChange,active,onExit,translation,setTranslation}:{textSize:ReturnType<typeof usePreviewTextSize>;resolvedDark:boolean;palette:PracticePalette;onPaletteChange:(palette:PracticePalette)=>void;translation:string;setTranslation:(value:string)=>void;mode:PracticeColourMode;onModeChange:(mode:PracticeColourMode)=>void;active:boolean;onExit:()=>void}){
 const [section,setSection]=useState("Languages");
 const [mobileDetail,setMobileDetail]=useState(false);
 useEffect(()=>{if(active)setMobileDetail(false);},[active]);
 const navigate=(name:string)=>{setSection(name);setMobileDetail(true);window.scrollTo({top:0,behavior:"instant"});};
 const [interfaceOpen,setInterfaceOpen]=useState(false);
 const interfaceBox=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!interfaceOpen)return;const close=(event:MouseEvent)=>{if(!interfaceBox.current?.contains(event.target as Node))setInterfaceOpen(false);};document.addEventListener("mousedown",close);return ()=>document.removeEventListener("mousedown",close);},[interfaceOpen]);
 const [order,setOrder]=useState(["Dutch","English","German"]);
 const [interfaceLanguage,setInterfaceLanguage]=useState("English");
 const [inactive,setInactive]=useState<string[]>([]);const [disabledDicts,setDisabledDicts]=useState<string[]>([]);
 const [picker,setPicker]=useState<"translation"|"learning"|null>(null);
 const changed=()=>{};

 return <section className={s.settings} data-mobile-detail={mobileDetail} aria-label="Settings">
 <h1 className={s.srOnly}>Settings</h1>
 <header className={s.mobilePageHeader}><button aria-label={mobileDetail?"Back to settings":"Back to app"} onClick={()=>{if(mobileDetail){setMobileDetail(false);window.scrollTo({top:0,behavior:"instant"});}else onExit();}}><ArrowLeft size={22}/></button><h2>{mobileDetail?section:"Settings"}</h2></header>
 <nav className={s.mobileMenu} aria-label="Mobile settings sections">{sections.map(({name,Icon})=><button key={name} onClick={()=>navigate(name)}><Icon size={20}/><span>{name}</span><ChevronRight size={17}/></button>)}</nav>
 <div className={s.layout}><nav className={s.sections} aria-label="Settings sections">{sections.map(({name,Icon})=><button key={name} aria-current={section===name?"page":undefined} onClick={()=>{setSection(name);}}><Icon size={16}/>{name}</button>)}</nav>
 <div key={section+String(mobileDetail)} className={s.content}>
 {section==="Languages"&&<><Panel title="Languages"><Row title="Interface language"><div ref={interfaceBox} className={s.interfaceSelect} onKeyDown={e=>{if(e.key==="Escape")setInterfaceOpen(false);}}><button className={s.selectTrigger} aria-expanded={interfaceOpen} aria-haspopup="listbox" aria-label="Interface language" onClick={()=>setInterfaceOpen(v=>!v)}>{interfaceLanguage}<ChevronDown size={13}/></button>{interfaceOpen&&<div className={s.interfaceMenu} role="listbox" aria-label="Available interface languages">{["English","Nederlands","Русский"].map(name=><button role="option" aria-selected={name===interfaceLanguage} key={name} onClick={()=>{setInterfaceLanguage(name);setInterfaceOpen(false);changed();}}>{name}{name===interfaceLanguage&&<Check size={13}/>}</button>)}</div>}</div></Row><Row title="Translation language" hint="Choose any language in the catalogue, or turn translations off."><div className={s.options}><button aria-pressed={translation==="Off"} onClick={()=>{setTranslation("Off");changed();}}>Off</button><button aria-haspopup="dialog" onClick={()=>setPicker("translation")}>{translation==="Off"?"Choose language":translation}<ChevronDown size={12}/></button></div></Row><div className={s.sample}><span className={s.caption}>TRANSLATION PREVIEW</span><p className={s.example}>zij woont in de gemeente Haarlem</p>{translation!=="Off"&&<p className={s.translation}>{translation==="English"?"She lives in the municipality of Haarlem.":translation==="Russian"||translation==="Русский"?"Она живёт в муниципалитете Харлем.":`Translation into ${translation} will appear here.`}</p>}</div></Panel><Panel title="Learning languages"><p className={s.hint}>Add languages and pause those you are not studying. Pausing preserves your progress. Keep at least one active language.</p><ol className={s.languageList}>{order.map((name,i)=><li key={name}><span><small>{i+1}</small>{name}</span><div className={s.languageActions}><button role="switch" aria-checked={!inactive.includes(name)} aria-label={`Study ${name}`} disabled={!inactive.includes(name)&&order.length-inactive.length===1} onClick={()=>{setInactive(items=>items.includes(name)?items.filter(x=>x!==name):[...items,name]);changed();}}>{inactive.includes(name)?"Paused":"Active"}</button><button aria-label={`Move ${name} up`} disabled={i===0} onClick={()=>{setOrder(items=>{const next=[...items];[next[i-1],next[i]]=[next[i],next[i-1]];return next;});changed();}}><ChevronUp size={16}/></button></div></li>)}</ol><button className={s.addButton} onClick={()=>setPicker("learning")}>Add language</button></Panel></>}
 {section==="Appearance"&&<Panel title="Appearance"><Row title="Colour mode"><Options label="Colour mode" options={["Light","Dark","System"]} value={mode} change={value=>onModeChange(value as PracticeColourMode)}/></Row><h3 className={s.subheading}>Theme</h3><div className={s.themes}>{practicePalettes.map(theme=><button key={theme.id} aria-pressed={palette===theme.id} onClick={()=>onPaletteChange(theme.id)} className={s.theme}><span aria-hidden="true" className={`${themeStyles.theme} ${s.swatches}`} data-practice-palette={theme.id} data-colour-mode={resolvedDark?"dark":"light"}><i/><i/><i/></span><strong>{theme.label}</strong><small>{palette===theme.id?<><Check size={12}/> Current</>:"Select"}</small></button>)}</div></Panel>}
 {section==="Appearance"&&<><Panel title="Text size"><p className={s.hint}>Cards and interface · saved for this {textSize.device==="phone"?"phone":"computer"}.</p><div className={s.textSizes} role="group" aria-label="Text size">{textSizes.map(size=><button key={size.id} aria-label={size.name} aria-pressed={textSize.size===size.id} disabled={!textSize.ready} onClick={()=>textSize.setSize(size.id)}>{size.label}</button>)}</div>{!textSize.stored&&<p role="status" className={s.hint}>Available for this visit. Your browser could not save this preference.</p>}<div className={`${s.cardPreview} ${libraryStyles.library}`} data-density="reading"><LibraryArticle preview model={goedGroups[1]} source="VanDale" study={{...studyDefaults,articleFrame:"framed",navigation:"close"}} onClose={()=>{}}/></div></Panel></>}

 {section==="Shortcuts"&&<Panel title="Training shortcuts"><p className={s.hint}>The shortcuts used in the current app. Shown here for reference.</p><div className={s.shortcuts}>{getTrainingHotkeys("en").map(item=><div key={item.key}><span>{item.description}</span><kbd>{item.key}</kbd></div>)}</div></Panel>}
 {section==="Dictionaries"&&<Panel><p className={s.dictionaryIntro}>Choose the dictionaries you want to use.</p><div className={s.dictionaryGroup}><Row title="Personal dictionary" hint="One dictionary for all languages. Always available; cannot be turned off."><button className={s.toggle} role="switch" aria-label="Personal dictionary is always enabled" aria-checked={true} disabled><span aria-hidden="true"/></button></Row><p className={s.hint}>Private · 72 entries · 24 expressions</p><div className={s.personalBreakdown}>{["Dutch","English","German"].map(name=><div key={name}><span>{name}</span><small>24 entries · 8 expressions</small></div>)}</div></div><p className={s.dictionaryIntro}>Published dictionaries</p><p className={s.hint}>Available for your active learning languages.</p>{order.filter(name=>!inactive.includes(name)).map(name=><div className={s.dictionaryGroup} key={name}><h3 className={s.subheading}>{name}</h3>{name==="Dutch"?<Row title="VanDale NT2" hint="Published · 2,000 entries"><button className={s.toggle} role="switch" aria-label="Use Dutch VanDale NT2" aria-checked={!disabledDicts.includes("dutch-published")} onClick={()=>{setDisabledDicts(items=>items.includes("dutch-published")?items.filter(x=>x!=="dutch-published"):[...items,"dutch-published"]);changed();}}><span aria-hidden="true"/></button></Row>:<p className={s.hint}>No published dictionaries available.</p>}</div>)}</Panel>}
 {section==="Billing & subscriptions"&&<><Panel title="Subscription"><Row title="Current plan"><span className={s.current}>Free</span></Row><Row title="Renewal date"><span className={s.current}>No active subscription</span></Row><button disabled className={s.addButton}>Explore plans</button></Panel><Panel title="Billing details"><p className={s.hint}>No billing details added.</p></Panel><Panel title="Invoices & payments"><p className={s.hint}>No payments to show.</p></Panel></>}
 {section==="Account"&&<Panel title="Account"><Row title="Profile"><span className={s.current}>Personal account</span></Row><Row title="Sign out"><button className={s.disabled} disabled>Sign out</button></Row></Panel>}

 </div></div>{picker&&<LanguagePicker title={picker==="learning"?"Add a learning language":"Translation language"} onClose={()=>setPicker(null)} onChoose={name=>{if(picker==="translation")setTranslation(name);else {setOrder(items=>items.includes(name)?items:[...items,name]);setInactive(items=>items.filter(x=>x!==name));}changed();}}/>}</section>;
}
function Panel({title,children}:{title?:string;children:React.ReactNode}){return <section className={s.panel}>{title&&<h2>{title}</h2>}{children}</section>}
function Row({title,hint,children}:{title:string;hint?:string;children:React.ReactNode}){return <div className={s.row}><div><h3>{title}</h3>{hint&&<p>{hint}</p>}</div><div>{children}</div></div>}
function Options({label,options,value,change}:{label:string;options:string[];value:string;change:(value:string)=>void}){return <div className={s.options} role="group" aria-label={label}>{options.map(option=><button key={option} aria-pressed={value===option} onClick={()=>change(option)}>{option}</button>)}</div>}
