"use client";
import React,{useEffect,useRef,useState} from "react";
import {PaletteChoices} from "@/components/practice/settings/PaletteChoices";
import {SettingsLayout,SettingsPanel,SettingsOptions,SettingsRow} from "@/components/practice/settings/SettingsLayout";
import {Check,ChevronUp,Languages,Palette,Keyboard,UserRound,Library,CreditCard,ChevronDown} from "lucide-react";
import {getTrainingHotkeys} from "@/components/training/trainingHotkeys";
import type {OnboardingLanguage} from "@/lib/onboardingI18n";
import {getUiMessages,formatUiMessage,formatUiCount} from "@/lib/uiMessages";
import {previewLanguageName} from "./previewLanguage";
import {textSizes} from "@/lib/reading/textScale";
import type {usePreviewTextSize} from "./usePreviewTextSize";
import {LanguagePicker} from "./LanguagePicker";
import {LibraryArticle} from "./LibraryArticle";
import {goedGroups} from "./GoedLibraryPreview";
import {studyDefaults} from "./libraryStudy";
import libraryStyles from "./library.module.css";
import s from "./settings.module.css";
import {type PracticePalette, type PracticeColourMode} from "@/components/practice/ui/appearance";
const sections=[{name:"Languages",Icon:Languages},{name:"Dictionaries",Icon:Library},{name:"Appearance",Icon:Palette},{name:"Shortcuts",Icon:Keyboard},{name:"Billing & subscriptions",Icon:CreditCard},{name:"Account",Icon:UserRound}];
const interfaceLanguages:{code:OnboardingLanguage;name:string}[]=[{code:"en",name:"English"},{code:"nl",name:"Nederlands"},{code:"ru",name:"Русский"}];
export function SettingsPrototype({textSize,resolvedDark,palette,onPaletteChange,mode,onModeChange,active,onExit,translation,setTranslation,interfaceLanguage,onInterfaceLanguageChange}:{textSize:ReturnType<typeof usePreviewTextSize>;resolvedDark:boolean;palette:PracticePalette;onPaletteChange:(palette:PracticePalette)=>void;translation:string;setTranslation:(value:string)=>void;mode:PracticeColourMode;onModeChange:(mode:PracticeColourMode)=>void;active:boolean;onExit:()=>void;interfaceLanguage:OnboardingLanguage;onInterfaceLanguageChange:(language:OnboardingLanguage)=>void}){
 const copy=getUiMessages(interfaceLanguage).settings;
 const nameOf=(name:string)=>previewLanguageName(interfaceLanguage,name);
 const sectionLabels:Record<string,string>={Languages:copy.languages,Dictionaries:copy.dictionaries,Appearance:copy.appearance,Shortcuts:copy.shortcuts,"Billing & subscriptions":copy.billing,Account:copy.account};
 const inventory=(entries:number,expressions:number)=>`${formatUiCount(interfaceLanguage,entries,copy,"entry")} · ${formatUiCount(interfaceLanguage,expressions,copy,"expression")}`;
 const [interfaceOpen,setInterfaceOpen]=useState(false);
 const interfaceBox=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!interfaceOpen)return;const close=(event:MouseEvent)=>{if(!interfaceBox.current?.contains(event.target as Node))setInterfaceOpen(false);};document.addEventListener("mousedown",close);return ()=>document.removeEventListener("mousedown",close);},[interfaceOpen]);
 const [order,setOrder]=useState(["Dutch","English","German"]);
 const [inactive,setInactive]=useState<string[]>([]);const [disabledDicts,setDisabledDicts]=useState<string[]>([]);
 const [picker,setPicker]=useState<"translation"|"learning"|null>(null);
 const changed=()=>{};

 return <><SettingsLayout className={s.settings} active={active} language={interfaceLanguage} items={sections.map(({name,Icon})=>({id:name,label:sectionLabels[name],Icon}))} onExit={onExit}>{section=><>
 {section==="Languages"&&<><Panel title={copy.languages}><Row title={copy.interfaceLanguage}><div ref={interfaceBox} className={s.interfaceSelect} onKeyDown={e=>{if(e.key==="Escape")setInterfaceOpen(false);}}><button className={s.selectTrigger} aria-expanded={interfaceOpen} aria-haspopup="listbox" aria-label={copy.interfaceLanguage} onClick={()=>setInterfaceOpen(v=>!v)}>{interfaceLanguages.find(option=>option.code===interfaceLanguage)?.name}<ChevronDown size={13}/></button>{interfaceOpen&&<div className={s.interfaceMenu} role="listbox" aria-label={copy.availableInterfaces}>{interfaceLanguages.map(({code,name})=><button role="option" aria-selected={code===interfaceLanguage} key={code} lang={code} onClick={()=>{onInterfaceLanguageChange(code);setInterfaceOpen(false);changed();}}>{name}{code===interfaceLanguage&&<Check size={13}/>}</button>)}</div>}</div></Row><Row title={copy.translationLanguage} hint={copy.translationHint}><div className={s.options}><button aria-pressed={translation==="Off"} onClick={()=>{setTranslation("Off");changed();}}>{copy.off}</button><button aria-haspopup="dialog" onClick={()=>setPicker("translation")}>{translation==="Off"?copy.chooseLanguage:nameOf(translation)}<ChevronDown size={12}/></button></div></Row><div className={s.sample}><span className={s.caption}>{copy.translationPreview}</span><p lang="nl" className={s.example}>zij woont in de gemeente Haarlem</p>{translation!=="Off"&&<p lang={translation==="English"?"en":translation==="Russian"||translation==="Русский"?"ru":interfaceLanguage} className={s.translation}>{translation==="English"?"She lives in the municipality of Haarlem.":translation==="Russian"||translation==="Русский"?"Она живёт в муниципалитете Харлем.":formatUiMessage(copy.translationFallback,{language:nameOf(translation)})}</p>}</div></Panel><Panel title={copy.learningLanguages}><p className={s.hint}>{copy.learningHint}</p><ol className={s.languageList}>{order.map((name,i)=><li key={name}><span><small>{i+1}</small>{nameOf(name)}</span><div className={s.languageActions}><button role="switch" aria-checked={!inactive.includes(name)} aria-label={formatUiMessage(copy.studyLanguage,{language:nameOf(name)})} disabled={!inactive.includes(name)&&order.length-inactive.length===1} onClick={()=>{setInactive(items=>items.includes(name)?items.filter(x=>x!==name):[...items,name]);changed();}}>{inactive.includes(name)?copy.paused:copy.active}</button><button aria-label={formatUiMessage(copy.moveLanguage,{language:nameOf(name)})} disabled={i===0} onClick={()=>{setOrder(items=>{const next=[...items];[next[i-1],next[i]]=[next[i],next[i-1]];return next;});changed();}}><ChevronUp size={16}/></button></div></li>)}</ol><button className={s.addButton} onClick={()=>setPicker("learning")}>{copy.addLanguage}</button></Panel></>}
 {section==="Appearance"&&<Panel title={copy.appearance}><Row title={copy.colourMode}><Options label={copy.colourMode} options={["Light","Dark","System"]} labels={getUiMessages(interfaceLanguage).builder.colourModes} value={mode} change={value=>onModeChange(value as PracticeColourMode)}/></Row><h3 className={s.subheading}>{copy.theme}</h3><PaletteChoices dark={resolvedDark} language={interfaceLanguage} palette={palette} onChange={onPaletteChange}/></Panel>}
 {section==="Appearance"&&<><Panel title={copy.textSize}><p className={s.hint}>{textSize.device==="phone"?copy.sizePhone:copy.sizeDesktop}</p><div className={s.textSizes} role="group" aria-label={copy.textSize}>{textSizes.map(size=><button key={size.id} aria-label={copy.sizes[size.id]} aria-pressed={textSize.size===size.id} disabled={!textSize.ready} onClick={()=>textSize.setSize(size.id)}>{size.label}</button>)}</div>{!textSize.stored&&<p role="status" className={s.hint}>{copy.sizeUnsaved}</p>}<div className={`${s.cardPreview} ${libraryStyles.library}`} data-density="reading"><LibraryArticle preview model={goedGroups[1]} source="VanDale" study={{...studyDefaults,articleFrame:"framed",navigation:"close"}} onClose={()=>{}}/></div></Panel></>}

 {section==="Shortcuts"&&<Panel title={copy.trainingShortcuts}><p className={s.hint}>{copy.shortcutsHint}</p><div className={s.shortcuts}>{getTrainingHotkeys(interfaceLanguage).map(item=><div key={item.key}><span>{item.description}</span><kbd>{item.key}</kbd></div>)}</div></Panel>}
 {section==="Dictionaries"&&<Panel><p className={s.dictionaryIntro}>{copy.dictionaryIntro}</p><div className={s.dictionaryGroup}><Row title={copy.personalDictionary} hint={copy.personalHint}><button className={s.toggle} role="switch" aria-label={copy.personalEnabled} aria-checked={true} disabled><span aria-hidden="true"/></button></Row><p className={s.hint}>{copy.private} · {inventory(72,24)}</p><div className={s.personalBreakdown}>{["Dutch","English","German"].map(name=><div key={name}><span>{nameOf(name)}</span><small>{inventory(24,8)}</small></div>)}</div></div><p className={s.dictionaryIntro}>{copy.publishedDictionaries}</p><p className={s.hint}>{copy.publishedHint}</p>{order.filter(name=>!inactive.includes(name)).map(name=><div className={s.dictionaryGroup} key={name}><h3 className={s.subheading}>{nameOf(name)}</h3>{name==="Dutch"?<Row title="VanDale NT2" hint={`${copy.published} · ${formatUiCount(interfaceLanguage,2000,copy,"entry")}`}><button className={s.toggle} role="switch" aria-label={formatUiMessage(copy.useDictionary,{language:nameOf("Dutch")})} aria-checked={!disabledDicts.includes("dutch-published")} onClick={()=>{setDisabledDicts(items=>items.includes("dutch-published")?items.filter(x=>x!=="dutch-published"):[...items,"dutch-published"]);changed();}}><span aria-hidden="true"/></button></Row>:<p className={s.hint}>{copy.noDictionaries}</p>}</div>)}</Panel>}
 {section==="Billing & subscriptions"&&<><Panel title={copy.subscription}><Row title={copy.currentPlan}><span className={s.current}>{copy.free}</span></Row><Row title={copy.renewal}><span className={s.current}>{copy.noSubscription}</span></Row><button disabled className={s.addButton}>{copy.explorePlans}</button></Panel><Panel title={copy.billingDetails}><p className={s.hint}>{copy.noBilling}</p></Panel><Panel title={copy.invoices}><p className={s.hint}>{copy.noPayments}</p></Panel></>}
 {section==="Account"&&<Panel title={copy.account}><Row title={copy.profile}><span className={s.current}>{copy.personalAccount}</span></Row><Row title={copy.signOut}><button className={s.disabled} disabled>{copy.signOut}</button></Row></Panel>}

 </>}</SettingsLayout>{picker&&<LanguagePicker title={picker==="learning"?copy.addLearningLanguage:copy.translationLanguage} onClose={()=>setPicker(null)} onChoose={name=>{if(picker==="translation")setTranslation(name);else {setOrder(items=>items.includes(name)?items:[...items,name]);setInactive(items=>items.filter(x=>x!==name));}changed();}}/>}</>;
}
function Panel({title,children}:{title?:string;children:React.ReactNode}){return <SettingsPanel title={title}>{children}</SettingsPanel>}
function Row({title,hint,children}:{title:string;hint?:string;children:React.ReactNode}){return <SettingsRow title={title} hint={hint} className={s.row}>{children}</SettingsRow>}
function Options({label,options,labels,value,change}:{label:string;options:string[];labels:Record<string,string>;value:string;change:(value:string)=>void}){return <SettingsOptions label={label} items={options.map(id=>({id,label:labels[id]}))} value={value} onChange={change}/>}
