import React,{useState} from 'react';
import {Search,BookOpen,Layers,Check} from 'lucide-react';
export function SourcePicker({locale,lists,dictionaries,draft,onChange}:any){
 const [search,setSearch]=useState(false),[query,setQuery]=useState(''),[kind,setKind]=useState('all');
 const labels=locale==='ru'?['Все','Словари','Коллекции','Поиск источников','Нет совпадений']:locale==='nl'?['Alles','Woordenboeken','Collecties','Bronnen zoeken','Geen resultaten']:['All','Dictionaries','Collections','Search sources','No matches'];
 const entries=[...dictionaries.map((x:any)=>({...x,kind:'dictionary'})),...lists.map((x:any)=>({...x,kind:'collection'}))];
 const large=entries.length>10;
 const visible=entries.filter(x=>(!search||kind==='all'||kind===x.kind)&&(!search||x.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())));
 return <div className="review-source"><div className="review-source-toolbar">{large&&<button type="button" aria-label={labels[3]} aria-expanded={search} onClick={()=>setSearch(!search)}><Search size={15}/></button>}{search&&<><input aria-label={labels[3]} placeholder={labels[3]} value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label={labels[0]} value={kind} onChange={e=>setKind(e.target.value)}>{['all','dictionary','collection'].map((k,i)=><option key={k} value={k}>{labels[i]}</option>)}</select></>}</div><div className="review-source-list">{visible.map(x=>{const active=x.kind==='dictionary'?draft.materialMode==='selected-dictionaries'&&draft.dictionaryIds?.includes(x.value):draft.materialMode==='collection'&&draft.listValue===x.value;return <button type="button" key={x.kind+':'+x.value} aria-pressed={Boolean(active)} onClick={()=>onChange((d:any)=>x.kind==='collection'?{...d,materialMode:'collection',listValue:x.value}:{...d,materialMode:'selected-dictionaries',dictionaryIds:d.materialMode==='selected-dictionaries'&&d.dictionaryIds?.includes(x.value)?d.dictionaryIds.filter((id:string)=>id!==x.value):[...(d.materialMode==='selected-dictionaries'?d.dictionaryIds??[]:[]),x.value]})}>{x.kind==='dictionary'?<BookOpen size={14}/>:<Layers size={14}/>}<span>{x.label}</span><small>{x.kind==='dictionary'?labels[1]:labels[2]}</small>{active&&<Check size={14}/>}</button>})}{!visible.length&&<p>{labels[4]}</p>}</div></div>;
}
