export const PLATFORM_V2_SUPPORTED_INTERFACE_LANGUAGES = [
  "en",
  "ru",
  "nl",
] as const;

export const PLATFORM_V2_REQUIRED_MESSAGE_KEYS = [
  "dictionary.name",
  "indicator.coreVocabulary.nt22000",
  "crossReference.see",
  "crossReference.follow",
  "senseCard.learning.start",
  "senseCard.known.mark",
  "senseCard.known.marked",
  "senseCard.known.undo",
  "senseCard.review.fail",
  "senseCard.review.hard",
  "senseCard.review.success",
  "senseCard.review.easy",
  "senseCard.translation.request",
  "senseCard.report",
  "senseCard.wordDetails.open",
  "partOfSpeech.afk",
  "partOfSpeech.bn",
  "partOfSpeech.bw",
  "partOfSpeech.lidw",
  "partOfSpeech.tsw",
  "partOfSpeech.tw",
  "partOfSpeech.vnw",
  "partOfSpeech.vv",
  "partOfSpeech.vw",
  "partOfSpeech.vz",
  "partOfSpeech.ww",
  "partOfSpeech.zn",
  "wordDetails.usageLabel",
  "wordDetails.form.plural",
  "wordDetails.form.diminutive",
  "wordDetails.form.verbForms",
  "wordDetails.form.inflectedForm",
  "wordDetails.form.comparative",
  "wordDetails.form.superlative",
  "wordDetails.form.derivation",
  "wordDetails.form.alternateHeadword",
  "wordDetails.form.conjugation",
  "wordDetails.feature.gender",
  "wordDetails.feature.plural",
  "wordDetails.feature.tense",
  "wordDetails.feature.personOrForm",
  "wordDetails.reference.headword",
  "wordDetails.reference.table",
] as const;

export type PlatformV2MessageKey =
  (typeof PLATFORM_V2_REQUIRED_MESSAGE_KEYS)[number];
