#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

port="${PORT:-3100}"
host="${HOST:-0.0.0.0}"
work_ref=""
expected_commit=""
usage() {
  cat <<'EOF'
Usage: scripts/ui-local-dev.sh [--port PORT] [--work-ref REF --expected-commit SHA]

Start apps/ui against the local Supabase stack with source evidence attached.
Without preview arguments, only a clean main checkout matching freshly fetched
origin/main is accepted. An intentional worktree preview requires both a durable
work reference and the exact 40-character commit currently checked out.

Options:
  --port PORT      UI port. Default: 3100.
  --work-ref REF   Issue/plan/reference for an intentional preview.
  --expected-commit SHA
                   Exact full SHA expected at the preview checkout.

Environment:
  PORT            UI port. Default: 3100.
  HOST            Reserved for future use. apps/ui dev script already binds 0.0.0.0.
  QA_TEST_USER_EMAIL Dev-login user email. Default: test@2000nl.local.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --port)
      port="${2:?Missing value for --port}"
      shift 2
      ;;
    --work-ref)
      work_ref="${2:?Missing value for --work-ref}"
      shift 2
      ;;
    --expected-commit)
      expected_commit="${2:?Missing value for --expected-commit}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -n "$work_ref" || -n "$expected_commit" ]]; then
  if [[ -z "$work_ref" || -z "$expected_commit" ]]; then
    echo "Preview startup requires both --work-ref and --expected-commit." >&2
    exit 1
  fi
  source_args=(verify --repo-root "$repo_root" --mode preview --work-ref "$work_ref" --expected-commit "$expected_commit" --format env)
else
  source_args=(verify --repo-root "$repo_root" --mode canonical --format env)
fi

# The verifier runs before Supabase discovery or Next startup. Its output is
# generated by this checkout and is shell-quoted before it is evaluated.
if ! source_environment="$(node "$repo_root/scripts/qa-source.mjs" "${source_args[@]}")"; then
  exit 1
fi
eval "$source_environment"

export NEXT_PUBLIC_APP_COMMIT="$QA_SOURCE_COMMIT"
export QA_SOURCE_MODE
export QA_SOURCE_WORK_REF
export QA_SOURCE_CHECKOUT_PATH
export QA_SOURCE_COMMIT
export QA_SOURCE_BRANCH
export QA_SOURCE_DIRTY
export QA_SOURCE_UPSTREAM
export QA_SOURCE_AHEAD
export QA_SOURCE_BEHIND
export QA_SOURCE_ORIGIN_MAIN
export QA_SOURCE_REMOTE_REFS
export QA_SOURCE_SQUASH_MERGED

if server_check_output="$(node "$repo_root/scripts/check-qa-server.mjs" \
  --port "$port" \
  --mode "$QA_SOURCE_MODE" \
  --work-ref "$QA_SOURCE_WORK_REF" \
  --expected-commit "$QA_SOURCE_COMMIT" 2>&1)"; then
  echo "$server_check_output"
  exit 0
else
  server_check_status=$?
  if [[ "$server_check_status" != "2" ]]; then
    echo "$server_check_output" >&2
    exit "$server_check_status"
  fi
fi

if ! command -v supabase >/dev/null 2>&1; then
  echo "Missing required command: supabase" >&2
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "Missing required command: npm" >&2
  exit 1
fi

status_env="$(cd "$repo_root" && supabase status -o env)"

get_env_value() {
  local key="$1"
  printf '%s\n' "$status_env" \
    | awk -F= -v key="$key" '$1 == key { value=$2; gsub(/^"|"$/, "", value); print value; exit }'
}

api_url="$(get_env_value API_URL)"
anon_key="$(get_env_value ANON_KEY)"
publishable_key="$(get_env_value PUBLISHABLE_KEY)"
secret_key="$(get_env_value SECRET_KEY)"
service_role_key="$(get_env_value SERVICE_ROLE_KEY)"

if [[ -z "$api_url" || -z "$anon_key" ]]; then
  echo "Local Supabase API_URL/ANON_KEY not found. Run scripts/db-local-supabase.sh start first." >&2
  exit 1
fi

export NEXT_PUBLIC_SUPABASE_URL="$api_url"
export NEXT_PUBLIC_SUPABASE_ANON_KEY="${publishable_key:-$anon_key}"
export NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY="${publishable_key:-$anon_key}"
export SUPABASE_URL="$api_url"
export SUPABASE_ANON_KEY="$anon_key"
export SUPABASE_SECRET_KEY="${secret_key:-$service_role_key}"
export SUPABASE_SERVICE_ROLE_KEY="$service_role_key"
export QA_TEST_USER_EMAIL="${QA_TEST_USER_EMAIL:-test@2000nl.local}"
export QA_TEST_USER_EMAIL_ALLOWLIST="${QA_TEST_USER_EMAIL_ALLOWLIST:-$QA_TEST_USER_EMAIL}"
export NEXT_PUBLIC_SITE_URL="http://localhost:$port"
export NEXT_DIST_DIR="${NEXT_DIST_DIR:-.next-dev}"

export APP_ROLLOUT_PROFILE="pilot"

echo "Starting UI against local Supabase:"
echo "  UI:       http://localhost:$port"
echo "  Supabase: $NEXT_PUBLIC_SUPABASE_URL"
echo "  Dev auth: http://localhost:$port/dev/test-login?redirectTo=/"
echo "  Health:   http://localhost:$port/api/health?deep=1"
echo "  Cache:    $NEXT_DIST_DIR"
echo "  Profile:  $APP_ROLLOUT_PROFILE (current)"
echo "  Source:   $QA_SOURCE_MODE / $QA_SOURCE_WORK_REF / $QA_SOURCE_COMMIT"
echo "  Checkout: $QA_SOURCE_CHECKOUT_PATH (dirty=$QA_SOURCE_DIRTY)"

cd "$repo_root/apps/ui"
node scripts/ensure-local-qa-account.js
exec npm run dev -- --port "$port"
