import hashlib,html,json,math,statistics
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4]/'Research/translation-eval/literal-accuracy-v1'
RUNS=['development-baseline','development-structure','development-conservative','heldout2-baseline','heldout2-structure']
HELPFUL={'development':['cow','monkey','butter','door','hare','cheese','nose','lamp','boat','rose'],'heldout2':['flowers','hair','molehill','quay','spoon','stone','rain']}
summary=[];cards=[]
for run in RUNS:
 manifest=json.loads((ROOT/run/'manifest.json').read_text());assessments=json.loads((ROOT/run/'assessments.json').read_text());byid={a['id']:a for a in assessments};ds=[];eligible=retained=emitted=0
 for job in manifest['jobs']:
  d=json.loads((ROOT/run/(job['id']+'.json')).read_text());a=byid[job['id']];ds.append(d)
  assert a['inputHash']==d['inputHash'] and a['responseHash']==d['responseHash']
  result=d['result'];idiom=next((c for c in (result or {}).get('contentTranslations',[]) if c['fieldId']=='idiom:0'),None)
  sourceid=job['id'].rsplit('-',1)[0];split=run.rsplit('-',1)[0]
  useful=sourceid in HELPFUL[split] and job['id'] not in ('boat-ru','molehill-ru')
  if run=='heldout2-structure' and job['id']=='oil-ru':useful=True
  eligible+=useful;emitted+=bool(useful and idiom and idiom.get('literalText'));retained+=bool(useful and idiom and idiom.get('literalText') and not any(f['category'].startswith('literal') for f in a['findings']))
  a['usefulImageEligible']=useful;a['usefulImageRetained']=bool(useful and idiom and idiom.get('literalText') and not any(f['category'].startswith('literal') for f in a['findings']))
  cls='bad' if any(f['severity'] in ('serious','delivery') for f in a['findings']) else 'warn' if a['findings'] else 'good'
  payload={'source':job['request'],'result':d['result'],'failure':d['failure'],'attempts':d['attempts'],'assessment':a}
  cards.append('<details class="'+cls+'" data-run="'+run+'"><summary>'+html.escape(run+' / '+job['id']+' — '+('accepted' if a['wholeCardAccepted'] else 'review'))+'</summary><pre>'+html.escape(json.dumps(payload,ensure_ascii=False,indent=2))+'</pre></details>')
 (ROOT/run/'assessments.json').write_text(json.dumps(assessments,ensure_ascii=False,indent=2)+'\n')
 findings=[f for a in assessments for f in a['findings']];times=sorted(d['elapsedMs'] for d in ds)
 summary.append({'run':run,'count':len(ds),'ready':sum(d['outcome']=='ready' for d in ds),'firstAttemptReady':sum(d['outcome']=='ready' and len(d['attempts'])==1 for d in ds),'attempts':sum(len(d['attempts']) for d in ds),'accepted':sum(a['wholeCardAccepted'] for a in assessments),'seriousImageErrors':sum(f['severity']=='serious' and f['category']=='literal-image' for f in findings),'seriousNaturalPrimaryErrors':sum(f['severity']=='serious' and not f['category'].startswith('literal') for f in findings),'minorFindings':sum(f['severity']=='minor' for f in findings),'deliveryFailures':sum(d['outcome']!='ready' for d in ds),'usefulImageEligible':eligible,'usefulImageEmitted':emitted,'usefulImageAcceptable':retained,'inputTokens':sum(d['usage']['prompt_tokens'] for d in ds),'outputTokens':sum(d['usage']['completion_tokens'] for d in ds),'reasoningTokensIncludedInOutput':sum(d['usage']['completion_tokens_details']['reasoning_tokens'] for d in ds),'medianMs':statistics.median(times),'p95Ms':times[math.ceil(len(times)*.95)-1]})
report={'decision':'Keep production v8/high. Structural candidate fixed known cat image failures in development, but held-out introduced a new wrong rain/drop image and one empty required field. Conservative candidate retained a cat error. No confirmed improvement without regression.','totalCalls':sum(s['attempts'] for s in summary),'method':'nonblind agent review, descriptive exploratory comparison; no human approval or statistical superiority claim','selectionBeforeHeldOut':json.loads((ROOT/'selection.json').read_text()),'selectionClarification':'Selection described19 retained development images: this meant19 emitted. One structural literal has a grammar finding, so18 are fully acceptable. Both availability and quality are reported separately.','heldOutCaveats':'Two previously seen idioms were removed before any held-out calls; superseded zero-call manifests retained. The synthetic stone headword is not part of its flies idiom; both runs receive exactly the same frozen source and its independent headword is scored as supplied. Minor judgements are subjective; raw outputs are retained. Natural paraphrases of social formulas are accepted when semantic meaning is preserved.','runs':summary}
(ROOT/'summary.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
options=''.join('<option>'+r+'</option>' for r in RUNS)
(ROOT/'index.html').write_text('''<!doctype html><meta charset="utf-8"><title>Literal-image accuracy experiment</title><style>body{max-width:1100px;margin:24px auto;padding:16px;font:16px system-ui}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f5f7;padding:16px}summary{cursor:pointer;padding:12px}details{border-left:4px solid #519579;margin:8px 0}.bad{border-color:#b94a53}.warn{border-color:#b98d3a}select,input{font:inherit;padding:8px;margin:10px}</style><h1>Дословный образ: v8 и два уточнения</h1><p>168 вызовов; 167 готовых ответов, 1 отказ строгого контракта. Production остаётся v8/high. Оценка агента, не слепая; без человеческого утверждения и статистического доказательства.</p><select id="run"><option value="">Все прогоны</option>'''+options+'''</select><input id="query" placeholder="Поиск: cat, rain, wire…"><pre>'''+html.escape(json.dumps(report,ensure_ascii=False,indent=2))+'</pre>'+''.join(cards)+'''<script>function filter(){for(const e of document.querySelectorAll('details'))e.hidden=(run.value&&e.dataset.run!==run.value)||!e.textContent.toLowerCase().includes(query.value.toLowerCase())}run.onchange=filter;query.oninput=filter;</script>''')
print(json.dumps(report['runs'],ensure_ascii=False,indent=2))
