export type AuthLanguage = "en" | "nl" | "ru";
export function detectAuthLanguage(language: string): AuthLanguage {
  return language.toLowerCase().startsWith("nl") ? "nl" : language.toLowerCase().startsWith("ru") ? "ru" : "en";
}
export const authCopy = {
  en: {title:"Your Dutch starts here",intro:"Sign in to keep your learning and progress together.",google:"Continue with Google",googleLoading:"Opening Google…",or:"or use email",email:"Email address",emailPlaceholder:"you@example.com",send:"Send login code",sending:"Sending code…",passwordless:"No password needed. New here? Your account is created when you sign in.",haveCode:"Already have a code?",codeTitle:"Check your email",codeIntro:"Enter the code sent to",code:"Enter your code",verify:"Verify code",verifying:"Signing in…",resend:"Resend code",resent:"A new code has been sent.",change:"Use different email",back:"Back to sign in",help:"Return to this app and paste the code from your email.",success:"Signed in successfully!",sendError:"We couldn’t send a code. Please try again.",verifyError:"That code didn’t work. Check it or request a new one.",googleError:"We couldn’t open Google sign-in. Please try again.",rateError:"Too many attempts. Please wait a moment before trying again.",expiredError:"This code has expired. Request a new one.",callbackError:"Sign-in wasn’t completed. Please try again."},
  nl: {title:"Hier begint je Nederlands",intro:"Log in om je leerwerk en voortgang te bewaren.",google:"Doorgaan met Google",googleLoading:"Google openen…",or:"of via e-mail",email:"E-mailadres",emailPlaceholder:"jij@voorbeeld.nl",send:"Stuur inlogcode",sending:"Code versturen…",passwordless:"Geen wachtwoord nodig. Nieuw hier? Je account wordt aangemaakt wanneer je inlogt.",haveCode:"Heb je al een code?",codeTitle:"Check je e-mail",codeIntro:"Voer de code in die is verstuurd naar",code:"Voer je code in",verify:"Verifieer code",verifying:"Inloggen…",resend:"Code opnieuw versturen",resent:"Er is een nieuwe code verstuurd.",change:"Ander e-mailadres gebruiken",back:"Terug naar inloggen",help:"Ga terug naar deze app en plak de code uit je e-mail.",success:"Inloggen succesvol!",sendError:"De code kon niet worden verstuurd. Probeer opnieuw.",verifyError:"Deze code werkt niet. Controleer de code of vraag een nieuwe aan.",googleError:"Google-aanmelding kon niet worden geopend. Probeer opnieuw.",rateError:"Te veel pogingen. Wacht even voordat je het opnieuw probeert.",expiredError:"Deze code is verlopen. Vraag een nieuwe aan.",callbackError:"Het inloggen is niet voltooid. Probeer opnieuw."},
  ru: {title:"Здесь начинается ваш нидерландский",intro:"Войдите, чтобы сохранять обучение и прогресс.",google:"Продолжить с Google",googleLoading:"Открываем Google…",or:"или по email",email:"Электронная почта",emailPlaceholder:"you@example.com",send:"Получить код",sending:"Отправляем код…",passwordless:"Пароль не нужен. Если вы здесь впервые, аккаунт создастся при входе.",haveCode:"Уже есть код?",codeTitle:"Проверьте почту",codeIntro:"Введите код, отправленный на",code:"Код из письма",verify:"Войти",verifying:"Входим…",resend:"Отправить код ещё раз",resent:"Новый код отправлен.",change:"Изменить адрес почты",back:"Вернуться ко входу",help:"Вернитесь в приложение и вставьте код из письма.",success:"Вы вошли в приложение!",sendError:"Не удалось отправить код. Попробуйте ещё раз.",verifyError:"Код не подошёл. Проверьте его или запросите новый.",googleError:"Не удалось открыть вход через Google. Попробуйте ещё раз.",rateError:"Слишком много попыток. Подождите немного и повторите.",expiredError:"Срок действия кода истёк. Запросите новый.",callbackError:"Вход не завершён. Попробуйте ещё раз."},
};
export function authErrorCopy(error: unknown, lang: AuthLanguage, action: "send" | "verify" | "google") {
  const code = error && typeof error === "object" && "code" in error ? String(error.code) : "";
  const t = authCopy[lang];
  if (["over_email_send_rate_limit","over_request_rate_limit"].includes(code)) return t.rateError;
  if (code === "otp_expired") return t.expiredError;
  return action === "send" ? t.sendError : action === "google" ? t.googleError : t.verifyError;
}
