import React from 'react';
import {fireEvent,render,screen,cleanup} from '@testing-library/react';
import {afterEach,expect,test,vi} from 'vitest';
import {TrainingOverview,type TrainingOverviewItem,type TrainingOverviewState} from '@/components/practice/TrainingOverview';
afterEach(cleanup);
const items:TrainingOverviewItem[]=[{id:'a',name:'Words',language:'Dutch',description:'Words · Direct',summary:'Dutch · 20 exercises',completedToday:12,meaningCount:36,sessionSize:20,canLaunch:true},{id:'b',name:'Idioms',language:'Dutch',description:'Idioms · Direct',summary:'Dutch · 10 exercises',completedToday:null,meaningCount:null,sessionSize:10,canLaunch:true}];
function setup(state:TrainingOverviewState={status:'ready',trainings:items,mainId:'a'}){const callbacks={onLaunch:vi.fn(),onResume:vi.fn(),onEdit:vi.fn(),onCreate:vi.fn(),onRetry:vi.fn()};render(<TrainingOverview state={state} {...callbacks}/>);return callbacks;}
test('edit and launch take the stable training identity directly',()=>{const c=setup();fireEvent.click(screen.getByRole('button',{name:'Edit Idioms'}));expect(c.onEdit).toHaveBeenCalledWith('b');fireEvent.click(screen.getByRole('button',{name:'Start training'}));expect(c.onLaunch).toHaveBeenCalledWith('a');expect(screen.queryByRole('dialog')).toBeNull();});
test('an unfinished session overrides the main routine and resumes its identity',()=>{const c=setup({status:'ready',trainings:items,mainId:'a',resume:{sessionId:'session-b',trainingId:'b',completed:3,total:10}});fireEvent.click(screen.getByRole('button',{name:'Continue training'}));expect(c.onResume).toHaveBeenCalledWith('session-b');expect(c.onLaunch).not.toHaveBeenCalled();expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuenow','3');});
test('unknown activity is not presented as zero',()=>{setup({status:'ready',trainings:items,mainId:'b'});expect(screen.getAllByText('—')).toHaveLength(2);});
test('loading, failure and empty are distinct actionable states',()=>{setup({status:'loading'});expect(screen.getByRole('status')).toHaveTextContent('Loading');expect(screen.queryByRole('button')).toBeNull();cleanup();let c=setup({status:'error',message:'Could not load training.'});fireEvent.click(screen.getByRole('button',{name:'Try again'}));expect(c.onRetry).toHaveBeenCalled();cleanup();c=setup({status:'ready',trainings:[],mainId:null});fireEvent.click(screen.getByRole('button',{name:'Create training'}));expect(c.onCreate).toHaveBeenCalled();});
test('unavailable training cannot start and explains why',()=>{setup({status:'ready',mainId:'a',trainings:[{...items[0],canLaunch:false,unavailableReason:'Source unavailable.'}]});expect(screen.getByRole('button',{name:'Start training'})).toBeDisabled();expect(screen.getByRole('status')).toHaveTextContent('Source unavailable.');});
test('a deleted main identity does not hide other saved training',()=>{setup({status:'ready',mainId:'deleted',trainings:[items[1]]});expect(screen.getByRole('button',{name:'Start Idioms'})).toBeEnabled();});
