import { act, renderHook, waitFor } from "@testing-library/react";
import { afterEach, expect, test, vi } from "vitest";
const { request } = vi.hoisted(() => ({ request: vi.fn() }));
vi.mock("@/lib/preferences/accountRequest", () => ({ authenticatedAccountRequest: request }));
import { useStudyTimeWindow } from "@/lib/training/studyTime/useStudyTimeWindow";
const page = { timezone: "UTC", asOf: "2026-09-30T10:00:00.000Z", startDate: "2026-09-30", endDate: "2026-09-30", coverageStartedAt: "2026-09-29T09:00:00Z", days: [{ date: "2026-09-30", activeMilliseconds: 70000 }] };
afterEach(() => { vi.clearAllMocks(); });
test("closed Statistics makes no request; opening authenticates a scoped read and rejects malformed results", async () => {
  request.mockResolvedValue({ ok: true, json: async () => page });
  const view = renderHook(({ open }) => useStudyTimeWindow("owner", "nl", "Today", open, 0), { initialProps: { open: false } });
  expect(request).not.toHaveBeenCalled();
  view.rerender({ open: true });
  await waitFor(() => expect(view.result.current.status).toBe("ready"));
  expect(request).toHaveBeenCalledWith("/api/training/study-time?period=Today&language=nl", "owner", expect.objectContaining({ method: "GET", signal: expect.any(AbortSignal) }));
  request.mockResolvedValue({ ok: true, json: async () => ({ ...page, days: [] }) });
  view.rerender({ open: false }); view.rerender({ open: true });
  await waitFor(() => expect(view.result.current.status).toBe("error"));
});
test("a late account response cannot overwrite the next account or expose the prior numbers", async () => {
  let resolve!: (value: unknown) => void;
  request.mockReturnValueOnce(new Promise(r => { resolve = r; })).mockResolvedValue({ ok: false });
  const view = renderHook(({ owner }) => useStudyTimeWindow(owner, "nl", "Today", true, 0), { initialProps: { owner: "first" } });
  const oldSignal = request.mock.calls[0][2].signal;
  view.rerender({ owner: "second" });
  expect(oldSignal.aborted).toBe(true);
  expect(view.result.current.status).not.toBe("ready");
  await waitFor(() => expect(view.result.current.status).toBe("error"));
  await act(async () => { resolve({ ok: true, json: async () => page }); });
  expect(view.result.current.status).toBe("error");
});
